[package]
name = "rusty-lance"
version = "0.1.0"
authors = ["Girts Folkmanis <girts@girts.me>"]

[dependencies]
piston = "0.37.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.47.0"
piston2d-opengl_graphics = "0.53.0"
lazy_static = "1.1.0"